package com.inst.greendao3_demo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bdpqchen.yellowpagesmodule.yellowpages.model.Phone;

import com.inst.greendao3_demo.dao.PhoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig phoneDaoConfig;

    private final PhoneDao phoneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        phoneDaoConfig = daoConfigMap.get(PhoneDao.class).clone();
        phoneDaoConfig.initIdentityScope(type);

        phoneDao = new PhoneDao(phoneDaoConfig, this);

        registerDao(Phone.class, phoneDao);
    }
    
    public void clear() {
        phoneDaoConfig.clearIdentityScope();
    }

    public PhoneDao getPhoneDao() {
        return phoneDao;
    }

}
